#!/usr/bin/env python

# Copyright 2013 Foxdog Studios Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

from argparse import ArgumentParser
import json
import sys


def try_get_value(conf_path, section, name):
    with open(conf_path) as conf_file:
        conf = json.load(conf_file)
    if section in conf:
        section = conf[section]
        if name in section:
            return section[name]
    return None


def build_argument_parser():
    parser = ArgumentParser()
    parser.add_argument('conf_file')
    parser.add_argument('section')
    parser.add_argument('option')
    return parser


def main(argv=None):
    if argv is None:
        argv = sys.argv
    args = build_argument_parser().parse_args(argv[1:])
    value = try_get_value(args.conf_file, args.section, args.option)
    if value is None:
        return 1
    print(value)
    return 0


if __name__ == '__main__':
    exit(main())

